name = "dchub"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "dchub"

[vars]
BOT_TOKEN="MTMyNDk5NjEzODI1MTU4MzU4MA.GnfLZp.eLaQrtV8Dlqb8xibgpIaWBN_gFGIHCuKxEXIOs"
CLOUDINARY_API_KEY="531949353138729"
CLOUDINARY_API_SECRET="djdmYOKolWMmIGA2Nbe2hd2CGyU"
CRON_SECRET="odGvtpgJFsjCBU6FwirT"
CUSTOM_PRISMA_URL="postgres://postgres.hpqmywbtjcsluqwxtzto:ac2475axn0104@aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true"
DISCORD_CLIENT_ID="1324996138251583580"
DISCORD_CLIENT_SECRET="eccT4N7yvdR20vuRyrbvLOfVTIhmjYV_"
NEXTAUTH_SECRET="iql1/ByzsZMyuU8tYx0Ds11DeJKOH1kzSuHnUJ4Fgsc="
NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME="dhdcfxsx7"
NEXT_PUBLIC_SITE_URL="https://dchubs.org"
NEXT_PUBLIC_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwcW15d2J0amNzbHVxd3h0enRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MDk5MTYsImV4cCI6MjA1OTA4NTkxNn0.ZA0UUmva0J_QPpIWu3dhxeJcY8GED21DXBohkjBBA5o"
NEXT_PUBLIC_SUPABASE_URL="https://hpqmywbtjcsluqwxtzto.supabase.co"
NEXT_PUBLIC_UPLOAD_PRESET="discordhub"
POSTGRES_DATABASE="postgres"
POSTGRES_HOST="db.hpqmywbtjcsluqwxtzto.supabase.co"
POSTGRES_PASSWORD="ac2475axn0104"
POSTGRES_PRISMA_URL="postgres://postgres.hpqmywbtjcsluqwxtzto:ac2475axn0104@aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require&supa=base-pooler.x"
POSTGRES_URL="postgres://postgres.hpqmywbtjcsluqwxtzto:ac2475axn0104@aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require&supa=base-pooler.x"
POSTGRES_URL_NON_POOLING="postgres://postgres.hpqmywbtjcsluqwxtzto:ac2475axn0104@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require"
POSTGRES_USER="postgres"
PRISMA_DISABLE_PREPARED_STATEMENTS="true"
SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwcW15d2J0amNzbHVxd3h0enRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MDk5MTYsImV4cCI6MjA1OTA4NTkxNn0.ZA0UUmva0J_QPpIWu3dhxeJcY8GED21DXBohkjBBA5o"
SUPABASE_JWT_SECRET="CB8AUBv9+3nToJPzGHDZC860Ws8rHvrPNtH8XiLvI4LdCrE8Qv0T9uJ6Hol2SJTKtNZOfm9r6jTR3HzEhtfHkA=="
SUPABASE_SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwcW15d2J0amNzbHVxd3h0enRvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MzUwOTkxNiwiZXhwIjoyMDU5MDg1OTE2fQ.igVOMfB2BqwXqrPYb7YG116y8DyJ6ByaUSPobvLWF5E"
SUPABASE_URL="https://hpqmywbtjcsluqwxtzto.supabase.co"