import { CategoryType } from './types';

export const Servercategories: CategoryType[] = [
  {
    id: '1',
    name: '遊戲',
    color: 'bg-green-600',
    selected: false,
  },
  {
    id: '2',
    name: '實況主',
    color: 'bg-purple-600',
    selected: false,
  },
  {
    id: '3',
    name: '粉絲社群',
    color: 'bg-pink-500',
    selected: false,
  },
  {
    id: '4',
    name: '繪師',
    color: 'bg-yellow-500',
    selected: false,
  },
  {
    id: '5',
    name: 'VTuber',
    color: 'bg-red-500',
    selected: false,
  },
  {
    id: '6',
    name: '音樂',
    color: 'bg-indigo-500',
    selected: false,
  },
  {
    id: '7',
    name: '交友',
    color: 'bg-blue-500',
    selected: false,
  },
  {
    id: '8',
    name: '動畫',
    color: 'bg-pink-600',
    selected: false,
  },
  {
    id: '9',
    name: '程式設計',
    color: 'bg-cyan-600',
    selected: false,
  },
  {
    id: '10',
    name: '標籤群',
    color: 'bg-orange-600',
    selected: false,
  },
  {
    id: '11',
    name: '教育',
    color: 'bg-teal-500',
    selected: false,
  },
  {
    id: '12',
    name: '日常',
    color: 'bg-sky-500',
    selected: false,
  },
  {
    id: '13',
    name: '心情樹洞',
    color: 'bg-rose-500',
    selected: false,
  },
  {
    id: '14',
    name: '攝影',
    color: 'bg-amber-600',
    selected: false,
  },
  {
    id: '15',
    name: '語言學習',
    color: 'bg-lime-500',
    selected: false,
  },
  {
    id: '16',
    name: '美食',
    color: 'bg-emerald-500',
    selected: false,
  },
  {
    id: '17',
    name: '電影',
    color: 'bg-red-600',
    selected: false,
  },
  {
    id: '18',
    name: '理財',
    color: 'bg-gray-600',
    selected: false,
  },
  {
    id: '19',
    name: '創作者合作',
    color: 'bg-fuchsia-600',
    selected: false,
  },
  {
    id: '20',
    name: '社群經營',
    color: 'bg-zinc-500',
    selected: false,
  },
  {
    id: '21',
    name: '支援群組',
    color: 'bg-teal-500',
    selected: false,
  },
];
