import type { ServerType, CategoryType, BotType } from "./types"

export const servers: ServerType[] = [
  {
    id: "1",
    name: "遊戲玩家聯盟",
    description: "台灣最大的遊戲玩家社群，討論各種遊戲、分享攻略、組隊開黑，歡迎所有遊戲愛好者加入！",
    tags: ["遊戲", "電競", "組隊", "攻略"],
    members: 15872,
    online: 3241,
    upvotes: 1287,
    icon: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=64&h=64&fit=crop&auto=format",
    banner: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=400&h=200&fit=crop&auto=format",
    featured: true,
    createdAt: "2023-05-15T08:30:00Z",
    owner: "遊戲達人",
    website: "https://example.com/gaming",
    inviteUrl: "https://discord.gg/example",
    longDescription:
      "台灣最大的遊戲玩家社群，我們提供一個友善的環境讓所有遊戲愛好者交流。無論您是休閒玩家還是專業電競選手，都能在這裡找到志同道合的朋友。我們定期舉辦各種遊戲比賽和活動，包括《英雄聯盟》、《Valorant》、《Apex 英雄》等熱門遊戲的比賽。加入我們，一起分享遊戲心得、攻略和最新資訊！",
    rules: [
      "尊重所有成員，禁止人身攻擊和歧視言論",
      "禁止發布垃圾訊息和廣告",
      "遵守Discord的服務條款",
      "禁止分享盜版內容和作弊工具",
      "違規者將被警告或移除",
    ],
    features: [
      "專業的遊戲討論頻道",
      "語音聊天室供組隊使用",
      "最新遊戲資訊和更新通知",
      "遊戲攻略和技巧分享",
      "定期舉辦遊戲比賽和活動",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1580327344181-c1163234e5a0?w=600&h=400&fit=crop&auto=format",
    ],
  },
  {
    id: "2",
    name: "程式設計交流站",
    description:
      "專為程式開發者打造的社群，分享程式設計知識、解決技術問題、討論最新技術趨勢，從初學者到專業開發者都歡迎！",
    tags: ["程式設計", "開發", "學習", "技術"],
    members: 8945,
    online: 1256,
    upvotes: 932,
    icon: "https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=64&h=64&fit=crop&auto=format",
    banner: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400&h=200&fit=crop&auto=format",
    featured: true,
    createdAt: "2023-07-22T14:15:00Z",
    owner: "程式大師",
    website: "https://example.com/coding",
    inviteUrl: "https://discord.gg/example",
    longDescription:
      "專為程式開發者打造的社群，無論您是初學者還是資深工程師，都能在這裡找到有價值的資源和交流機會。我們的社群涵蓋多種程式語言和技術領域，包括 Web 開發、移動應用開發、人工智能、數據科學等。成員可以分享程式設計知識、解決技術問題、討論最新技術趨勢，並尋找項目合作夥伴。我們還定期舉辦線上講座和工作坊，邀請業界專家分享經驗。",
    rules: [
      "尊重所有成員，保持專業和友善的交流",
      "在適當的頻道發布內容",
      "提問前先搜索是否有類似問題",
      "分享代碼時使用代碼塊格式",
      "禁止發布侵權內容和商業廣告",
    ],
    features: [
      "按程式語言和技術分類的討論頻道",
      "代碼審查和問題解答",
      "項目展示和合作機會",
      "技術資源分享",
      "就業和面試經驗交流",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=600&h=400&fit=crop&auto=format",
    ],
  },
  {
    id: "3",
    name: "動漫迷聚集地",
    description:
      "這是一個專為動漫愛好者打造的社群，我們討論最新的動漫、漫畫、輕小說，分享同人創作，舉辦觀影會，一起享受二次元的樂趣！",
    tags: ["動漫", "漫畫", "輕小說", "同人"],
    members: 12456,
    online: 2187,
    upvotes: 1045,
    icon: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=64&h=64&fit=crop&auto=format",
    banner: "https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?w=400&h=200&fit=crop&auto=format",
    featured: true,
    createdAt: "2023-03-10T10:45:00Z",
    owner: "動漫控",
    website: "https://example.com/anime",
    inviteUrl: "https://discord.gg/example",
    longDescription:
      "這是一個專為動漫愛好者打造的社群，我們熱愛並討論各種動漫、漫畫和輕小說。在這裡，您可以找到最新的動漫資訊、季度新番討論、經典作品回顧，以及同人創作分享。我們定期舉辦線上觀影會，一起觀看新番或經典作品，並進行即時討論。社群中還有角色扮演、繪畫和創作分享的專區，讓您展示自己的才華。無論您是資深動漫迷還是剛接觸動漫的新人，都能在這裡找到屬於自己的二次元天地！",
    rules: [
      "尊重所有成員和創作者",
      "使用適當的標籤標記敏感內容",
      "在相應的頻道發布內容",
      "禁止發布非法內容和盜版資源",
      "討論時避免劇透，或使用劇透標記",
    ],
    features: [
      "按類型和季度分類的動漫討論頻道",
      "同人創作和繪畫分享",
      "每週線上觀影會",
      "動漫新聞和資訊更新",
      "角色扮演和主題活動",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1578632292335-df3abbb0d586?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1613376023733-0a73315d9b06?w=600&h=400&fit=crop&auto=format",
    ],
  },
  {
    id: "4",
    name: "Minecraft 創世神伺服器",
    description:
      "歡迎來到我們的Minecraft伺服器！這裡有生存、創造、小遊戲等多種模式，適合各種玩家。我們的社群友善且活躍，定期舉辦活動和比賽。",
    tags: ["Minecraft", "遊戲", "創造", "生存"],
    members: 7823,
    online: 945,
    upvotes: 687,
    icon: "https://images.unsplash.com/photo-1587573089734-599d584d49e7?w=64&h=64&fit=crop&auto=format",
    banner: "https://images.unsplash.com/photo-1607513746994-51f730a44832?w=400&h=200&fit=crop&auto=format",
    featured: false,
    createdAt: "2023-08-05T16:20:00Z",
    owner: "方塊大師",
    website: "https://example.com/minecraft",
    inviteUrl: "https://discord.gg/example",
    longDescription:
      "歡迎來到我們的 Minecraft 創世神伺服器！我們提供多種遊戲模式，包括生存、創造、空島生存、小遊戲等，適合不同喜好的玩家。伺服器採用最新版本，並安裝了多種實用插件，提升遊戲體驗。我們的社群友善且活躍，管理團隊負責任且公正，確保所有玩家都能享受遊戲樂趣。我們定期舉辦建築比賽、尋寶活動和團隊挑戰，豐富遊戲內容。無論您是建築愛好者、紅石工程師還是冒險家，都能在這裡找到屬於自己的天地！",
    rules: [
      "禁止使用作弊模組和外掛",
      "尊重其他玩家的建築和領地",
      "禁止惡意破壞和偷竊",
      "禁止使用不當語言和騷擾行為",
      "遵守伺服器管理員的指示",
    ],
    features: [
      "多種遊戲模式：生存、創造、空島生存",
      "經濟系統和玩家商店",
      "領地保護和鎖箱插件",
      "定期舉辦建築比賽和活動",
      "活躍的玩家社群和幫助系統",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1627856013091-fed6e4e30025?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1623934199716-dc28818a6ec7?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1626379953822-baec19c3accd?w=600&h=400&fit=crop&auto=format",
    ],
  },
  {
    id: "5",
    name: "音樂分享俱樂部",
    description: "分享你喜愛的音樂，發現新的音樂風格，討論音樂製作和樂器演奏，還有定期的線上音樂會和DJ表演！",
    tags: ["音樂", "分享", "DJ", "樂器"],
    members: 5467,
    online: 732,
    upvotes: 421,
    icon: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=64&h=64&fit=crop&auto=format",
    banner: "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=400&h=200&fit=crop&auto=format",
    featured: false,
    createdAt: "2023-09-18T12:10:00Z",
    owner: "音樂達人",
    website: "https://example.com/music",
    inviteUrl: "https://discord.gg/example",
    longDescription:
      "音樂分享俱樂部是一個專為音樂愛好者打造的社群，無論您喜歡什麼風格的音樂，都能在這裡找到志同道合的朋友。我們鼓勵成員分享自己喜愛的音樂，發現新的音樂風格，討論音樂製作和樂器演奏技巧。社群中有專門的頻道討論不同音樂類型，包括古典、搖滾、電子、嘻哈、爵士等。我們還定期舉辦線上音樂會、DJ表演和音樂製作工作坊，讓成員展示才華並相互學習。無論您是音樂創作者、表演者還是純粹的聽眾，都能在這裡找到屬於自己的音樂天地！",
    rules: [
      "尊重所有音樂風格和創作者",
      "分享音樂時提供適當的資訊和來源",
      "禁止分享盜版音樂和侵權內容",
      "在適當的頻道發布內容",
      "給予建設性的評論和反饋",
    ],
    features: [
      "按音樂類型分類的討論頻道",
      "音樂推薦和分享",
      "樂器學習和技巧交流",
      "音樂製作和混音討論",
      "定期線上音樂會和DJ表演",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&h=400&fit=crop&auto=format",
    ],
  },
  {
    id: "6",
    name: "電影愛好者",
    description:
      "討論各種電影、影集、導演作品和演員表現。每週舉辦線上觀影會，一起欣賞經典和新上映的電影，分享影評和推薦。",
    tags: ["電影", "影集", "影評", "觀影"],
    members: 6234,
    online: 843,
    upvotes: 512,
    icon: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=64&h=64&fit=crop&auto=format",
    banner: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400&h=200&fit=crop&auto=format",
    featured: false,
    createdAt: "2023-10-25T09:30:00Z",
    owner: "影評人",
    website: "https://example.com/movies",
    inviteUrl: "https://discord.gg/example",
    longDescription:
      "電影愛好者社群是一個專為電影和影集愛好者打造的交流平台。在這裡，我們討論各種類型的電影和影集，從好萊塢大片到獨立製作，從經典名作到最新上映。社群成員可以分享自己的觀影心得、影評和推薦，探討導演的拍攝手法、演員的表演和劇情發展。我們每週都會舉辦線上觀影會，一起欣賞精選電影，並進行即時討論。此外，我們還有專門的頻道討論電影理論、電影史和幕後製作，適合各種層次的電影愛好者參與。",
    rules: [
      "尊重所有成員的觀點和意見",
      "討論時避免劇透，或使用劇透標記",
      "禁止分享盜版電影和非法資源",
      "給予建設性的評論和反饋",
      "在適當的頻道發布內容",
    ],
    features: [
      "按類型和地區分類的電影討論頻道",
      "每週線上觀影會",
      "影評和推薦分享",
      "電影新聞和上映資訊",
      "電影理論和幕後製作討論",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=600&h=400&fit=crop&auto=format",
    ],
  },
  {
    id: "7",
    name: "攝影分享社",
    description:
      "分享你的攝影作品，學習攝影技巧，討論相機設備，一起探索攝影的無限可能。適合從入門到專業的所有攝影愛好者。",
    tags: ["攝影", "相機", "技巧", "作品"],
    members: 4532,
    online: 621,
    upvotes: 378,
    icon: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=64&h=64&fit=crop&auto=format",
    banner: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=400&h=200&fit=crop&auto=format",
    featured: false,
    createdAt: "2023-11-12T15:45:00Z",
    owner: "攝影師",
    website: "https://example.com/photography",
    inviteUrl: "https://discord.gg/example",
    longDescription:
      "攝影分享社是一個專為攝影愛好者打造的社群，無論您是剛接觸攝影的新手還是經驗豐富的專業攝影師，都能在這裡找到有價值的資源和交流機會。我們鼓勵成員分享自己的攝影作品，學習和討論各種攝影技巧，包括構圖、光線運用、後期處理等。社群中有專門的頻道討論相機設備、鏡頭選擇和攝影配件，幫助成員做出明智的購買決定。我們還定期舉辦攝影主題挑戰、作品點評和線上工作坊，幫助成員提升攝影技能。無論您喜歡風景、人像、街拍還是其他類型的攝影，都能在這裡找到志同道合的朋友！",
    rules: [
      "尊重所有成員和他們的作品",
      "給予建設性的評論和反饋",
      "標明自己作品的拍攝資訊（如相機、鏡頭、設置）",
      "禁止發布侵權內容和不當圖片",
      "在適當的頻道發布內容",
    ],
    features: [
      "按攝影類型分類的作品分享頻道",
      "攝影技巧和教學資源",
      "相機設備和器材討論",
      "後期處理和編輯技巧",
      "定期攝影主題挑戰和作品點評",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1554048612-b6a482bc67e5?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1520549233664-03f65c1d1327?w=600&h=400&fit=crop&auto=format",
    ],
  },
  {
    id: "8",
    name: "語言學習交流",
    description:
      "多語言學習社群，提供英語、日語、韓語、法語等語言學習資源和交流機會。語言交換、學習方法分享、文化討論，一起進步！",
    tags: ["語言", "學習", "英語", "日語"],
    members: 9876,
    online: 1432,
    upvotes: 876,
    icon: "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=64&h=64&fit=crop&auto=format",
    banner: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400&h=200&fit=crop&auto=format",
    featured: false,
    createdAt: "2023-06-30T11:20:00Z",
    owner: "語言達人",
    website: "https://example.com/languages",
    inviteUrl: "https://discord.gg/example",
    longDescription:
      "語言學習交流是一個多語言學習社群，為語言學習者提供資源和交流機會。我們的社群涵蓋多種語言，包括英語、日語、韓語、法語、德語、西班牙語等。成員可以參與語言交換，與母語者練習對話，提升口語和聽力能力。我們提供各種學習資源，包括教材推薦、學習方法分享、考試準備指南等。此外，我們還有文化討論頻道，探討各國的文化、歷史和風俗習慣，幫助學習者更全面地理解目標語言。無論您是語言初學者還是多語言達人，都能在這裡找到適合自己的學習環境和交流夥伴！",
    rules: [
      "尊重所有成員和他們的文化背景",
      "鼓勵使用目標語言進行交流",
      "給予建設性的糾正和反饋",
      "禁止使用不當語言和冒犯性言論",
      "在適當的語言頻道發布內容",
    ],
    features: [
      "按語言分類的學習頻道",
      "語言交換配對系統",
      "學習資源和教材分享",
      "語法問題解答和討論",
      "文化交流和討論",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1503551723145-6c040742065b?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1456081445452-e990a1ce9b68?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=600&h=400&fit=crop&auto=format",
    ],
  },
  {
    id: "9",
    name: "Valorant 戰隊招募",
    description:
      "專為 Valorant 玩家打造的社群，尋找隊友、組建戰隊、分享戰術、討論更新。從銅牌到不朽，歡迎所有技術水平的玩家！",
    tags: ["Valorant", "FPS", "電競", "組隊"],
    members: 5678,
    online: 987,
    upvotes: 432,
    icon: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=64&h=64&fit=crop&auto=format",
    banner: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=200&fit=crop&auto=format",
    featured: false,
    createdAt: "2024-01-15T18:30:00Z",
    owner: "Valorant大師",
    website: "https://example.com/valorant",
    inviteUrl: "https://discord.gg/example",
    longDescription:
      "Valorant 戰隊招募是一個專為 Valorant 玩家打造的社群，幫助玩家尋找隊友、組建戰隊、分享戰術和討論遊戲更新。無論您是剛開始玩 Valorant 的新手，還是經驗豐富的高階玩家，都能在這裡找到適合自己水平的隊友。我們的社群按段位分類，從銅牌到不朽，方便玩家找到相近水平的隊友。我們提供各種資源，包括地圖戰術、特工使用指南、槍械控制技巧等。此外，我們還定期舉辦內部比賽和訓練賽，幫助玩家提升技術水平。加入我們，一起在 Valorant 的世界中征戰！",
    rules: [
      "尊重所有成員，禁止辱罵和攻擊性言論",
      "禁止分享作弊工具和外掛",
      "組隊時清楚說明自己的段位和期望",
      "給予建設性的反饋和建議",
      "遵守遊戲的服務條款和行為準則",
    ],
    features: [
      "按段位分類的組隊頻道",
      "戰術分享和討論",
      "特工使用指南和技巧",
      "遊戲更新和資訊通知",
      "定期舉辦內部比賽和訓練賽",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1580327344181-c1163234e5a0?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=600&h=400&fit=crop&auto=format",
    ],
  },
  {
    id: "10",
    name: "創業者社群",
    description:
      "連結有志創業的夥伴，分享創業經驗、市場分析、募資技巧和商業模式。一起討論創新想法，尋找合作機會，共同成長！",
    tags: ["創業", "商業", "投資", "創新"],
    members: 3245,
    online: 412,
    upvotes: 287,
    icon: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=64&h=64&fit=crop&auto=format",
    banner: "https://images.unsplash.com/photo-1556761175-4b46a572b786?w=400&h=200&fit=crop&auto=format",
    featured: false,
    createdAt: "2024-02-20T14:10:00Z",
    owner: "創業導師",
    website: "https://example.com/startup",
    inviteUrl: "https://discord.gg/example",
    longDescription:
      "創業者社群是一個連結有志創業的夥伴的平台，我們致力於幫助創業者分享經驗、解決問題、尋找資源和合作機會。在這裡，您可以分享創業經驗、市場分析、募資技巧和商業模式，討論創新想法，尋找潛在的合作夥伴和投資者。我們的社群成員來自各行各業，包括科技、電商、服務業、製造業等，提供多元的視角和經驗。我們定期舉辦線上講座和工作坊，邀請成功的創業者和投資人分享經驗和見解。無論您是正在醞釀創業想法，還是已經創立公司，都能在這裡找到有價值的資源和支持！",
    rules: [
      "尊重所有成員的意見和建議",
      "禁止發布垃圾訊息和無關廣告",
      "保護知識產權，尊重商業機密",
      "給予建設性的反饋和建議",
      "在適當的頻道發布內容",
    ],
    features: [
      "創業經驗和案例分享",
      "市場分析和商業模式討論",
      "募資和投資機會",
      "法律和稅務諮詢",
      "創業資源和工具推薦",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=600&h=400&fit=crop&auto=format",
    ],
  },
]

export const categories: CategoryType[] = [
  {
    id: "1",
    name: "遊戲",
    color: "bg-blue-500",
    selected: true,
  },
  {
    id: "2",
    name: "動漫",
    color: "bg-pink-500",
    selected: false,
  },
  {
    id: "3",
    name: "程式設計",
    color: "bg-green-500",
    selected: false,
  },
  {
    id: "4",
    name: "音樂",
    color: "bg-purple-500",
    selected: false,
  },
  {
    id: "5",
    name: "電影",
    color: "bg-red-500",
    selected: false,
  },
  {
    id: "6",
    name: "攝影",
    color: "bg-yellow-500",
    selected: false,
  },
  {
    id: "7",
    name: "語言學習",
    color: "bg-indigo-500",
    selected: false,
  },
  {
    id: "8",
    name: "創業",
    color: "bg-orange-500",
    selected: false,
  },
  {
    id: "9",
    name: "藝術",
    color: "bg-teal-500",
    selected: false,
  },
  {
    id: "10",
    name: "科技",
    color: "bg-cyan-500",
    selected: false,
  },
]

export const bots: BotType[] = [
  {
    id: "1",
    name: "音樂大師",
    description:
      "高品質音樂機器人，支援多種平台，包括 YouTube、Spotify、SoundCloud 等。提供清晰的音質和豐富的播放控制功能。",
    tags: ["音樂", "娛樂", "多媒體"],
    servers: 12500,
    users: 980000,
    upvotes: 4567,
    icon: "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=64&h=64&fit=crop&auto=format",
    banner: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&h=200&fit=crop&auto=format",
    featured: true,
    createdAt: "2022-03-15T10:30:00Z",
    prefix: "!music",
    developer: "音樂科技團隊",
    website: "https://example.com/musicbot",
    inviteUrl: "https://discord.com/oauth2/example",
    supportServer: "https://discord.gg/example",
    verified: true,
    longDescription:
      "音樂大師是一款專為 Discord 設計的高品質音樂機器人，支援多種音樂平台，包括 YouTube、Spotify、SoundCloud、Apple Music 等。我們提供清晰的音質和豐富的播放控制功能，讓您的語音頻道充滿美妙的音樂。機器人支援播放列表、隊列管理、音量控制、音效調整等功能，滿足各種音樂需求。您還可以使用我們的搜索功能，快速找到想聽的歌曲，或者使用自動播放功能，讓機器人根據您的音樂喜好推薦歌曲。音樂大師運行穩定，反應迅速，是您 Discord 伺服器的理想音樂播放解決方案！",
    commands: [
      {
        name: "play",
        description: "播放音樂",
        usage: "!music play <歌曲名稱或URL>",
        category: "播放控制",
      },
      {
        name: "pause",
        description: "暫停當前播放的音樂",
        usage: "!music pause",
        category: "播放控制",
      },
      {
        name: "skip",
        description: "跳過當前播放的歌曲",
        usage: "!music skip",
        category: "播放控制",
      },
      {
        name: "queue",
        description: "顯示當前播放隊列",
        usage: "!music queue",
        category: "隊列管理",
      },
      {
        name: "volume",
        description: "調整音量",
        usage: "!music volume <1-100>",
        category: "設置",
      },
    ],
    features: [
      "支援多種音樂平台",
      "高品質音樂播放",
      "豐富的播放控制功能",
      "播放列表和隊列管理",
      "音量和音效調整",
      "自動播放和推薦功能",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&h=400&fit=crop&auto=format",
    ],
  },
  {
    id: "2",
    name: "管理助手",
    description:
      "全能的伺服器管理機器人，提供自動審核、歡迎訊息、身分組管理、日誌記錄等功能。保持伺服器井然有序的最佳助手。",
    tags: ["管理", "審核", "日誌", "實用工具"],
    servers: 18700,
    users: 1250000,
    upvotes: 6234,
    icon: "https://images.unsplash.com/photo-1633409361618-c73427e4e206?w=64&h=64&fit=crop&auto=format",
    banner: "https://images.unsplash.com/photo-1586892477838-2b96e85e0f96?w=400&h=200&fit=crop&auto=format",
    featured: true,
    createdAt: "2021-11-20T14:45:00Z",
    prefix: "!admin",
    developer: "管理系統開發團隊",
    website: "https://example.com/adminbot",
    inviteUrl: "https://discord.com/oauth2/example",
    supportServer: "https://discord.gg/example",
    verified: true,
    longDescription:
      "管理助手是一款全能的 Discord 伺服器管理機器人，專為伺服器管理員和版主設計，提供全面的管理工具和功能。我們的機器人可以幫助您自動審核新成員和訊息內容，防止垃圾訊息和不當內容；設置自定義的歡迎訊息和離開訊息；管理身分組和權限；記錄伺服器活動日誌，包括訊息編輯和刪除、成員加入和離開等。此外，管理助手還提供自動警告和懲罰系統，可以根據違規行為自動執行相應的懲罰措施。我們的機器人界面友好，設置簡單，是保持伺服器井然有序的最佳助手！",
    commands: [
      {
        name: "kick",
        description: "踢出伺服器成員",
        usage: "!admin kick <@用戶> [原因]",
        category: "管理",
      },
      {
        name: "ban",
        description: "封禁伺服器成員",
        usage: "!admin ban <@用戶> [原因] [刪除訊息天數]",
        category: "管理",
      },
      {
        name: "mute",
        description: "禁言伺服器成員",
        usage: "!admin mute <@用戶> <時間> [原因]",
        category: "管理",
      },
      {
        name: "warn",
        description: "警告伺服器成員",
        usage: "!admin warn <@用戶> [原因]",
        category: "管理",
      },
      {
        name: "logs",
        description: "查看伺服器日誌",
        usage: "!admin logs [類型] [數量]",
        category: "日誌",
      },
    ],
    features: [
      "自動審核和內容過濾",
      "自定義歡迎和離開訊息",
      "身分組和權限管理",
      "詳細的伺服器活動日誌",
      "自動警告和懲罰系統",
      "防垃圾訊息和防洗版功能",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=600&h=400&fit=crop&auto=format",
    ],
  },
  {
    id: "3",
    name: "遊戲夥伴",
    description:
      "專為遊戲玩家設計的機器人，提供遊戲資訊查詢、戰績統計、組隊配對、遊戲活動提醒等功能。支援多種熱門遊戲。",
    tags: ["遊戲", "統計", "組隊", "資訊"],
    servers: 9800,
    users: 820000,
    upvotes: 3789,
    icon: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=64&h=64&fit=crop&auto=format",
    banner: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=200&fit=crop&auto=format",
    featured: true,
    createdAt: "2022-05-08T09:15:00Z",
    prefix: "!game",
    developer: "遊戲科技工作室",
    website: "https://example.com/gamebot",
    inviteUrl: "https://discord.com/oauth2/example",
    supportServer: "https://discord.gg/example",
    verified: true,
    longDescription:
      "遊戲夥伴是一款專為遊戲玩家設計的 Discord 機器人，旨在提升您的遊戲體驗和社交互動。我們的機器人支援多種熱門遊戲，包括《英雄聯盟》、《Valorant》、《Apex 英雄》、《Fortnite》、《Minecraft》等。您可以使用我們的機器人查詢遊戲資訊、統計個人和團隊戰績、尋找組隊夥伴、接收遊戲活動和更新提醒。此外，遊戲夥伴還提供遊戲內物品和角色資訊查詢、遊戲新聞摘要、遊戲攻略和技巧分享等功能。我們的目標是成為您遊戲旅程中的得力助手，幫助您更好地享受遊戲樂趣並與其他玩家建立聯繫！",
    commands: [
      {
        name: "stats",
        description: "查詢遊戲戰績",
        usage: "!game stats <遊戲名稱> <玩家ID>",
        category: "戰績",
      },
      {
        name: "lfg",
        description: "尋找組隊夥伴",
        usage: "!game lfg <遊戲名稱> <人數> [段位] [模式]",
        category: "組隊",
      },
      {
        name: "info",
        description: "查詢遊戲資訊",
        usage: "!game info <遊戲名稱> [內容類型]",
        category: "資訊",
      },
      {
        name: "news",
        description: "獲取遊戲新聞",
        usage: "!game news <遊戲名稱> [數量]",
        category: "資訊",
      },
      {
        name: "reminder",
        description: "設置遊戲活動提醒",
        usage: "!game reminder <遊戲名稱> <活動名稱> <時間>",
        category: "提醒",
      },
    ],
    features: [
      "多遊戲戰績統計和查詢",
      "組隊配對和尋找夥伴",
      "遊戲資訊和物品查詢",
      "遊戲活動和更新提醒",
      "遊戲新聞和攻略分享",
      "自定義遊戲通知設置",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1542751110-97427bbecf20?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1580327344181-c1163234e5a0?w=600&h=400&fit=crop&auto=format",
    ],
  },
  {
    id: "4",
    name: "經濟系統",
    description:
      "完整的伺服器經濟系統，包括貨幣、商店、工作、賭場、搶劫等多種經濟活動。增加伺服器互動性和趣味性的絕佳選擇。",
    tags: ["經濟", "貨幣", "遊戲", "互動"],
    servers: 7500,
    users: 650000,
    upvotes: 2876,
    icon: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=64&h=64&fit=crop&auto=format",
    banner: "https://images.unsplash.com/photo-1565514020179-026b92b4a0b0?w=400&h=200&fit=crop&auto=format",
    featured: false,
    createdAt: "2022-08-12T16:40:00Z",
    prefix: "!eco",
    developer: "經濟遊戲工作室",
    website: "https://example.com/economybot",
    inviteUrl: "https://discord.com/oauth2/example",
    supportServer: "https://discord.gg/example",
    verified: false,
    longDescription:
      "經濟系統是一款為 Discord 伺服器打造的完整經濟模擬機器人，旨在增加伺服器的互動性和趣味性。我們的機器人提供豐富的經濟活動和遊戲，包括貨幣系統、商店和物品交易、工作和任務系統、賭場和小遊戲、搶劫和冒險活動等。成員可以通過各種方式賺取虛擬貨幣，購買物品和特權，參與經濟活動，與其他成員互動。管理員可以自定義貨幣名稱、經濟規則、物品和商店內容，打造專屬於您伺服器的經濟系統。經濟系統機器人不僅增加了伺服器的活躍度，還為成員提供了更多互動和娛樂的機會，是提升伺服器氛圍的絕佳選擇！",
    commands: [
      {
        name: "balance",
        description: "查看貨幣餘額",
        usage: "!eco balance [@用戶]",
        category: "貨幣",
      },
      {
        name: "work",
        description: "工作賺取貨幣",
        usage: "!eco work",
        category: "賺錢",
      },
      {
        name: "shop",
        description: "查看商店物品",
        usage: "!eco shop [頁碼]",
        category: "商店",
      },
      {
        name: "buy",
        description: "購買商店物品",
        usage: "!eco buy <物品ID> [數量]",
        category: "商店",
      },
      {
        name: "gamble",
        description: "賭博遊戲",
        usage: "!eco gamble <金額>",
        category: "賭場",
      },
    ],
    features: [
      "完整的虛擬貨幣系統",
      "多樣化的賺錢方式",
      "自定義商店和物品",
      "賭場和小遊戲",
      "搶劫和冒險活動",
      "經濟排行榜和統計",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1580519542036-c47de6196ba5?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&h=400&fit=crop&auto=format",
    ],
  },
  {
    id: "5",
    name: "活動助理",
    description:
      "幫助伺服器組織和管理各種活動的機器人，包括投票、抽獎、問卷調查、活動報名等功能。提升伺服器活躍度的好幫手。",
    tags: ["活動", "投票", "抽獎", "實用工具"],
    servers: 6200,
    users: 580000,
    upvotes: 2345,
    icon: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=64&h=64&fit=crop&auto=format",
    banner: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=400&h=200&fit=crop&auto=format",
    featured: false,
    createdAt: "2022-10-05T11:25:00Z",
    prefix: "!event",
    developer: "活動策劃團隊",
    website: "https://example.com/eventbot",
    inviteUrl: "https://discord.com/oauth2/example",
    supportServer: "https://discord.gg/example",
    verified: false,
    longDescription:
      "活動助理是一款專為 Discord 伺服器設計的活動管理機器人，旨在幫助伺服器管理員和活動組織者輕鬆策劃和管理各種活動。我們的機器人提供多種活動相關功能，包括投票系統、抽獎活動、問卷調查、活動報名和管理、倒數計時器、活動提醒等。使用活動助理，您可以輕鬆創建互動式的投票和調查，組織公平透明的抽獎活動，管理活動報名和參與者名單，設置活動倒數計時和提醒。我們的機器人界面直觀，操作簡單，適合各種類型和規模的活動。無論是小型聚會還是大型比賽，活動助理都能幫助您提升活動的組織效率和參與度，是提升伺服器活躍度的好幫手！",
    commands: [
      {
        name: "poll",
        description: "創建投票",
        usage: "!event poll <問題> <選項1> <選項2> [選項3] ...",
        category: "投票",
      },
      {
        name: "giveaway",
        description: "創建抽獎活動",
        usage: "!event giveaway <時間> <獎品> [獲獎人數] [要求]",
        category: "抽獎",
      },
      {
        name: "survey",
        description: "創建問卷調查",
        usage: "!event survey <標題> <問題1> <問題2> ...",
        category: "調查",
      },
      {
        name: "signup",
        description: "創建活動報名",
        usage: "!event signup <活動名稱> <時間> <人數上限> [描述]",
        category: "報名",
      },
      {
        name: "countdown",
        description: "設置倒數計時器",
        usage: "!event countdown <活動名稱> <時間> [頻道]",
        category: "提醒",
      },
    ],
    features: [
      "互動式投票和調查系統",
      "公平透明的抽獎活動",
      "活動報名和參與者管理",
      "問卷調查和反饋收集",
      "活動倒數計時和提醒",
      "活動數據統計和分析",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1556155092-490a1ba16284?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1551818255-e6e10975bc17?w=600&h=400&fit=crop&auto=format",
    ],
  },
  {
    id: "6",
    name: "圖像創作師",
    description:
      "強大的圖像生成和編輯機器人，支援 AI 繪圖、圖像編輯、表情符號創建、迷因生成等功能。釋放創意的完美工具。",
    tags: ["圖像", "AI", "創意", "藝術"],
    servers: 5400,
    users: 490000,
    upvotes: 2123,
    icon: "https://images.unsplash.com/photo-1561948955-570b270e7c36?w=64&h=64&fit=crop&auto=format",
    banner: "https://images.unsplash.com/photo-1579547621113-e4bb2a19bdd6?w=400&h=200&fit=crop&auto=format",
    featured: false,
    createdAt: "2023-01-18T13:50:00Z",
    prefix: "!art",
    developer: "創意工作室",
    website: "https://example.com/artbot",
    inviteUrl: "https://discord.com/oauth2/example",
    supportServer: "https://discord.gg/example",
    verified: false,
    longDescription:
      "圖像創作師是一款結合了最新 AI 技術的圖像生成和編輯機器人，為 Discord 用戶提供豐富的創意工具。我們的機器人支援多種圖像相關功能，包括 AI 繪圖和圖像生成、圖像編輯和處理、表情符號和頭像創建、迷因和有趣圖片生成等。使用圖像創作師，您可以通過文字描述生成獨特的 AI 藝術作品，編輯和美化現有圖片，創建自定義的表情符號和頭像，生成有趣的迷因和圖片。我們的機器人使用先進的 AI 模型和圖像處理技術，確保高質量的輸出結果。無論您是藝術愛好者、內容創作者還是普通用戶，圖像創作師都能幫助您釋放創意，豐富您的 Discord 體驗！",
    commands: [
      {
        name: "generate",
        description: "生成 AI 圖像",
        usage: "!art generate <描述> [風格] [尺寸]",
        category: "AI 繪圖",
      },
      {
        name: "edit",
        description: "編輯圖像",
        usage: "!art edit <圖片> <效果> [參數]",
        category: "圖像編輯",
      },
      {
        name: "emoji",
        description: "創建表情符號",
        usage: "!art emoji <圖片/描述> [名稱]",
        category: "創建",
      },
      {
        name: "meme",
        description: "生成迷因",
        usage: "!art meme <模板> <上文> <下文>",
        category: "迷因",
      },
      {
        name: "avatar",
        description: "創建頭像",
        usage: "!art avatar <描述/風格> [形狀]",
        category: "創建",
      },
    ],
    features: [
      "AI 驅動的圖像生成",
      "多種圖像編輯和濾鏡效果",
      "自定義表情符號和頭像創建",
      "迷因和有趣圖片生成",
      "高質量輸出和多種風格選項",
      "批量處理和圖像集合",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=600&h=400&fit=crop&auto=format",
    ],
  },
  {
    id: "7",
    name: "學習助手",
    description: "專為學生和學習者設計的機器人，提供筆記管理、提醒功能、知識問答、翻譯工具、計算器等學習輔助功能。",
    tags: ["學習", "教育", "筆記", "實用工具"],
    servers: 4800,
    users: 420000,
    upvotes: 1876,
    icon: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=64&h=64&fit=crop&auto=format",
    banner: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400&h=200&fit=crop&auto=format",
    featured: false,
    createdAt: "2023-03-22T10:15:00Z",
    prefix: "!study",
    developer: "教育科技團隊",
    website: "https://example.com/studybot",
    inviteUrl: "https://discord.com/oauth2/example",
    supportServer: "https://discord.gg/example",
    verified: false,
    longDescription:
      "學習助手是一款專為學生和學習者設計的 Discord 機器人，旨在幫助用戶更有效地學習和管理學習資源。我們的機器人提供多種學習輔助功能，包括筆記管理和組織、學習提醒和計時器、知識問答和解釋、翻譯和語言工具、計算器和公式求解等。使用學習助手，您可以在 Discord 中創建和管理筆記，設置學習提醒和截止日期通知，獲取知識問題的解答和解釋，使用多語言翻譯工具，進行數學計算和公式求解。我們的機器人支援多種學科和領域，包括數學、科學、語言、歷史等，是學生、教師和終身學習者的理想學習夥伴！",
    commands: [
      {
        name: "note",
        description: "創建和管理筆記",
        usage: "!study note <add/list/view/delete> [標題] [內容]",
        category: "筆記",
      },
      {
        name: "remind",
        description: "設置學習提醒",
        usage: "!study remind <時間> <內容>",
        category: "提醒",
      },
      {
        name: "ask",
        description: "提問知識問題",
        usage: "!study ask <問題>",
        category: "知識",
      },
      {
        name: "translate",
        description: "翻譯文本",
        usage: "!study translate <語言> <文本>",
        category: "語言",
      },
      {
        name: "calc",
        description: "計算數學表達式",
        usage: "!study calc <表達式>",
        category: "計算",
      },
    ],
    features: [
      "筆記創建和管理系統",
      "學習提醒和截止日期通知",
      "知識問答和解釋",
      "多語言翻譯工具",
      "數學計算器和公式求解",
      "學習資源和參考資料",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=600&h=400&fit=crop&auto=format",
    ],
  },
  {
    id: "8",
    name: "歡迎大使",
    description:
      "專業的伺服器歡迎機器人，提供自定義歡迎訊息、成員驗證、身分組分配、伺服器導覽等功能。給新成員最好的第一印象。",
    tags: ["歡迎", "驗證", "身分組", "管理"],
    servers: 8900,
    users: 780000,
    upvotes: 3456,
    icon: "https://images.unsplash.com/photo-1530811761207-8d9d22f0a141?w=64&h=64&fit=crop&auto=format",
    banner: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=400&h=200&fit=crop&auto=format",
    featured: false,
    createdAt: "2022-12-10T15:30:00Z",
    prefix: "!welcome",
    developer: "社群管理團隊",
    website: "https://example.com/welcomebot",
    inviteUrl: "https://discord.com/oauth2/example",
    supportServer: "https://discord.gg/example",
    verified: true,
    longDescription:
      "歡迎大使是一款專業的 Discord 伺服器歡迎機器人，旨在為新加入的成員提供溫馨的歡迎體驗，並協助伺服器管理員進行成員管理。我們的機器人提供多種歡迎相關功能，包括自定義歡迎訊息和圖片、成員驗證和篩選、自動身分組分配、伺服器導覽和規則確認等。使用歡迎大使，您可以創建個性化的歡迎訊息，包括文字、圖片和嵌入內容；設置成員驗證系統，防止機器人和惡意用戶；自動分配身分組和權限；提供伺服器導覽和頻道介紹。我們的機器人界面友好，設置簡單，是提升新成員體驗和伺服器安全性的理想選擇！",
    commands: [
      {
        name: "setup",
        description: "設置歡迎系統",
        usage: "!welcome setup <頻道> [選項]",
        category: "設置",
      },
      {
        name: "message",
        description: "設置歡迎訊息",
        usage: "!welcome message <文本/嵌入> [內容]",
        category: "設置",
      },
      {
        name: "verify",
        description: "設置驗證系統",
        usage: "!welcome verify <類型> [選項]",
        category: "驗證",
      },
      {
        name: "autorole",
        description: "設置自動身分組",
        usage: "!welcome autorole <add/remove> <身分組>",
        category: "身分組",
      },
      {
        name: "guide",
        description: "設置伺服器導覽",
        usage: "!welcome guide <add/list/remove> [標題] [內容]",
        category: "導覽",
      },
    ],
    features: [
      "自定義歡迎訊息和圖片",
      "成員驗證和篩選系統",
      "自動身分組分配",
      "伺服器導覽和規則確認",
      "離開訊息和成員統計",
      "多語言支援和本地化",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1581089781785-603411fa81e5?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1563986768711-b3bde3dc821e?w=600&h=400&fit=crop&auto=format",
    ],
  },
  {
    id: "9",
    name: "直播通知",
    description:
      "追蹤和通知 Twitch、YouTube、Facebook Gaming 等平台的直播動態。當您關注的實況主開播時，自動發送通知到指定頻道。",
    tags: ["直播", "通知", "Twitch", "YouTube"],
    servers: 5100,
    users: 460000,
    upvotes: 2012,
    icon: "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=64&h=64&fit=crop&auto=format",
    banner: "https://images.unsplash.com/photo-1603739903239-8b6e64c3b185?w=400&h=200&fit=crop&auto=format",
    featured: false,
    createdAt: "2023-02-05T17:20:00Z",
    prefix: "!stream",
    developer: "直播科技團隊",
    website: "https://example.com/streambot",
    inviteUrl: "https://discord.com/oauth2/example",
    supportServer: "https://discord.gg/example",
    verified: false,
    longDescription:
      "直播通知是一款專為遊戲和內容創作社群設計的 Discord 機器人，幫助您追蹤和通知各大直播平台的實況動態。我們的機器人支援多個直播平台，包括 Twitch、YouTube、Facebook Gaming、Trovo 等。當您關注的實況主開始直播時，機器人會自動發送通知到指定的 Discord 頻道，包括直播標題、遊戲類別、縮圖和直播連結。您可以自定義通知格式和內容，設置通知角色標記，過濾特定遊戲或類別的直播。此外，機器人還提供實況主統計資訊、直播時間表和直播剪輯功能。無論您是遊戲公會、粉絲社群還是內容創作者，直播通知都能幫助您緊跟喜愛的實況主的直播動態！",
    commands: [
      {
        name: "add",
        description: "添加實況主追蹤",
        usage: "!stream add <平台> <實況主名稱> [頻道]",
        category: "追蹤",
      },
      {
        name: "list",
        description: "列出已追蹤的實況主",
        usage: "!stream list [平台]",
        category: "追蹤",
      },
      {
        name: "remove",
        description: "移除實況主追蹤",
        usage: "!stream remove <平台> <實況主名稱>",
        category: "追蹤",
      },
      {
        name: "format",
        description: "設置通知格式",
        usage: "!stream format <模板>",
        category: "設置",
      },
      {
        name: "filter",
        description: "設置遊戲過濾器",
        usage: "!stream filter <add/remove> <遊戲名稱>",
        category: "設置",
      },
    ],
    features: [
      "多平台直播追蹤和通知",
      "自定義通知格式和內容",
      "通知角色標記和提醒",
      "遊戲和類別過濾",
      "實況主統計和資訊",
      "直播時間表和提醒",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1561736778-92e52a7769ef?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1603739903239-8b6e64c3b185?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1603184017213-2ac8a41d3b10?w=600&h=400&fit=crop&auto=format",
    ],
  },
  {
    id: "10",
    name: "翻譯精靈",
    description:
      "即時多語言翻譯機器人，支援 100 多種語言。可自動翻譯訊息、設置雙語頻道、翻譯語音內容，打破語言障礙的最佳工具。",
    tags: ["翻譯", "語言", "國際化", "實用工具"],
    servers: 7200,
    users: 630000,
    upvotes: 2789,
    icon: "https://images.unsplash.com/photo-1493612276216-ee3925520721?w=64&h=64&fit=crop&auto=format",
    banner: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=200&fit=crop&auto=format",
    featured: false,
    createdAt: "2022-09-28T12:35:00Z",
    prefix: "!translate",
    developer: "語言科技團隊",
    website: "https://example.com/translatebot",
    inviteUrl: "https://discord.com/oauth2/example",
    supportServer: "https://discord.gg/example",
    verified: true,
    longDescription:
      "翻譯精靈是一款功能強大的多語言翻譯機器人，旨在打破 Discord 伺服器中的語言障礙，促進全球用戶的交流和溝通。我們的機器人支援 100 多種語言的即時翻譯，包括英語、中文、日語、韓語、西班牙語、法語、德語等主要語言。您可以使用翻譯精靈即時翻譯訊息，設置雙語或多語言頻道，自動翻譯特定用戶或語言的訊息，甚至翻譯語音內容的文字記錄。機器人使用先進的神經網絡翻譯技術，確保翻譯的準確性和自然度。無論您是國際社群、多語言遊戲公會還是語言學習群組，翻譯精靈都能幫助您克服語言障礙，促進成員之間的有效溝通！",
    commands: [
      {
        name: "translate",
        description: "翻譯文本",
        usage: "!translate <目標語言> <文本>",
        category: "翻譯",
      },
      {
        name: "auto",
        description: "設置自動翻譯",
        usage: "!translate auto <on/off> [源語言] [目標語言]",
        category: "設置",
      },
      {
        name: "channel",
        description: "設置雙語頻道",
        usage: "!translate channel <設置/移除> [源語言] [目標語言]",
        category: "設置",
      },
      {
        name: "user",
        description: "設置用戶翻譯",
        usage: "!translate user <@用戶> <源語言> <目標語言>",
        category: "設置",
      },
      {
        name: "languages",
        description: "列出支援的語言",
        usage: "!translate languages [搜尋詞]",
        category: "資訊",
      },
    ],
    features: [
      "支援 100 多種語言的即時翻譯",
      "雙語和多語言頻道設置",
      "自動訊息翻譯",
      "用戶和語言過濾",
      "語音內容文字記錄翻譯",
      "高準確度神經網絡翻譯",
    ],
    screenshots: [
      "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1523731407965-2430cd12f5e4?w=600&h=400&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1526378722484-bd91ca387e72?w=600&h=400&fit=crop&auto=format",
    ],
  },
]

