name: Deploy to Cloudflare Workers

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: bun-deps-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            bun-deps-

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build
        env:
          CUSTOM_PRISMA_URL: ${{ secrets.CUSTOM_PRISMA_URL }}
          POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}

      - name: Deploy to Cloudflare Workers
        run: bunx wrangler deploy --env production
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
