name: Vercel Preview URL Comment

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  vercel_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep 30 seconds
        run: sleep 30

      - name: Vercel Preview URL
        uses: zentered/vercel-preview-url@v1.1.9
        id: vercel_preview_url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_project_id: 'prj_U10w7yPhzVzgeGCR05jNMYq7Qgt3'

      - name: Create Comment with URL
        uses: actions/github-script@v6
        if: steps.vercel_preview_url.outputs.preview_url
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const url = `https://${{ steps.vercel_preview_url.outputs.preview_url }}`;
            const message = `Vercel Preview URL: ${url}`;
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });

      - name: Get URL(for debug)
        run: echo "https://${{ steps.vercel_preview_url.outputs.preview_url }}"