name: GitHub Actions Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Vercel env vars
        run: vercel env pull .env --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build
        env:
          # .env.local 會自動被 dotenv 讀取，如果你使用 dotenv
          # 如果需要明確 export，可加以下兩行：
          CUSTOM_PRISMA_URL: ${{ secrets.CUSTOM_PRISMA_URL }}
          POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}

